# Generated by Django 4.2.30 on 2026-06-09 23:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='setups/', verbose_name='Imagen')),
                ('categoria', models.CharField(choices=[('gamer', 'Gamer'), ('oficina', 'Oficina'), ('minimalista', 'Minimalista'), ('streaming', 'Streaming'), ('workstation', 'Workstation')], default='gamer', max_length=20, verbose_name='Categoria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ram_tamano', models.CharField(blank=True, help_text='Ej: 16GB, 32GB', max_length=30, verbose_name='RAM - Tamano')),
                ('ram_frecuencia', models.CharField(blank=True, help_text='Ej: 3200MHz', max_length=30, verbose_name='RAM - Frecuencia')),
                ('cpu_marca', models.CharField(blank=True, help_text='Ej: AMD Ryzen 5 5600X', max_length=80, verbose_name='CPU - Marca / Modelo')),
                ('cpu_socket', models.CharField(blank=True, help_text='Ej: AM4, LGA1700', max_length=30, verbose_name='CPU - Socket')),
                ('cpu_frecuencia', models.CharField(blank=True, help_text='Ej: 3.7GHz', max_length=30, verbose_name='CPU - Frecuencia')),
                ('cpu_nucleos', models.PositiveIntegerField(blank=True, help_text='Ej: 6', null=True, verbose_name='CPU - Nucleos')),
                ('gpu_marca', models.CharField(blank=True, help_text='Ej: NVIDIA RTX 3060', max_length=80, verbose_name='GPU - Marca / Modelo')),
                ('gpu_frecuencia', models.CharField(blank=True, help_text='Ej: 1.78GHz', max_length=30, verbose_name='GPU - Frecuencia')),
                ('gpu_vram', models.CharField(blank=True, help_text='Ej: 12GB', max_length=30, verbose_name='GPU - VRAM')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], default='SSD', max_length=10, verbose_name='Tipo')),
                ('tamano', models.CharField(help_text='Ej: 1TB, 500GB', max_length=30, verbose_name='Tamano')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='core.setup')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.setup')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.setup')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('setup', 'usuario')},
            },
        ),
    ]
